// Code generated by hz. DO NOT EDIT.

package auth

import "context"

type AuthService interface {
	Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error)
	Refresh(ctx context.Context, req *RefreshRequest) (*RefreshResponse, error)
	Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error)
}
