// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/user/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_ERROR_REASON_UNSPECIFIED ErrorReason = 0
	ErrorReason_USER_NOT_FOUND           ErrorReason = 1
	ErrorReason_USERNAME_EXISTS          ErrorReason = 2
	ErrorReason_EMAIL_EXISTS             ErrorReason = 3
	ErrorReason_INVALID_CREDENTIALS      ErrorReason = 4
	ErrorReason_INTERNAL                 ErrorReason = 5
	ErrorReason_PERMISSION_DENIED        ErrorReason = 6
	ErrorReason_INVALID_PAGE_TOKEN       ErrorReason = 7
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "ERROR_REASON_UNSPECIFIED",
		1: "USER_NOT_FOUND",
		2: "USERNAME_EXISTS",
		3: "EMAIL_EXISTS",
		4: "INVALID_CREDENTIALS",
		5: "INTERNAL",
		6: "PERMISSION_DENIED",
		7: "INVALID_PAGE_TOKEN",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED": 0,
		"USER_NOT_FOUND":           1,
		"USERNAME_EXISTS":          2,
		"EMAIL_EXISTS":             3,
		"INVALID_CREDENTIALS":      4,
		"INTERNAL":                 5,
		"PERMISSION_DENIED":        6,
		"INVALID_PAGE_TOKEN":       7,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_proto_user_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_proto_user_v1_error_reason_proto protoreflect.FileDescriptor

const file_proto_user_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	" proto/user/v1/error_reason.proto\x12\vapi.user.v1\x1a\x13errors/errors.proto*\xe6\x01\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x0eUSER_NOT_FOUND\x10\x01\x1a\x04\xa8E\x94\x03\x12\x19\n" +
	"\x0fUSERNAME_EXISTS\x10\x02\x1a\x04\xa8E\x99\x03\x12\x16\n" +
	"\fEMAIL_EXISTS\x10\x03\x1a\x04\xa8E\x99\x03\x12\x1d\n" +
	"\x13INVALID_CREDENTIALS\x10\x04\x1a\x04\xa8E\x91\x03\x12\x12\n" +
	"\bINTERNAL\x10\x05\x1a\x04\xa8E\xf4\x03\x12\x1b\n" +
	"\x11PERMISSION_DENIED\x10\x06\x1a\x04\xa8E\x93\x03\x12\x1c\n" +
	"\x12INVALID_PAGE_TOKEN\x10\a\x1a\x04\xa8E\x90\x03B Z\x1ekratos-template/api/user/v1;v1b\x06proto3"

var (
	file_proto_user_v1_error_reason_proto_rawDescOnce sync.Once
	file_proto_user_v1_error_reason_proto_rawDescData []byte
)

func file_proto_user_v1_error_reason_proto_rawDescGZIP() []byte {
	file_proto_user_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_proto_user_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_v1_error_reason_proto_rawDesc), len(file_proto_user_v1_error_reason_proto_rawDesc)))
	})
	return file_proto_user_v1_error_reason_proto_rawDescData
}

var file_proto_user_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_user_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.user.v1.ErrorReason
}
var file_proto_user_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_v1_error_reason_proto_init() }
func file_proto_user_v1_error_reason_proto_init() {
	if File_proto_user_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_v1_error_reason_proto_rawDesc), len(file_proto_user_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_proto_user_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_proto_user_v1_error_reason_proto_enumTypes,
	}.Build()
	File_proto_user_v1_error_reason_proto = out.File
	file_proto_user_v1_error_reason_proto_goTypes = nil
	file_proto_user_v1_error_reason_proto_depIdxs = nil
}
