// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"

	authmw "kratos-template/app/gateway/pkg/middleware/auth"
)

func rootMw() []app.HandlerFunc {
	if mw := authmw.Default(); mw != nil {
		return []app.HandlerFunc{mw}
	}
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listusersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createuserMw() []app.HandlerFunc {
	// your code...
	return nil
}
