// Code generated by hz. DO NOT EDIT.

package user

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"go.uber.org/fx"
	"kratos-template/app/gateway/biz/handler"
	userservice "kratos-template/app/gateway/biz/service/user"
)

func Register(r map[string]fx.Option) {
	r["user"] = fx.Module("user",
		fx.Provide(userservice.NewService, handler.NewUserHandler),
		fx.Invoke(RegisterRouter),
	)
}

func RegisterRouter(r *server.Hertz, h *handler.UserHandler) {
	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_v1 := _api.Group("/v1", _v1Mw()...)
			_v1.GET("/users", append(_listusersMw(), h.ListUsers)...)
			_users := _v1.Group("/users", _usersMw()...)
			_users.DELETE("/:id", append(_deleteuserMw(), h.DeleteUser)...)
			_users.GET("/:id", append(_getuserMw(), h.GetUser)...)
			_users.PUT("/:id", append(_updateuserMw(), h.UpdateUser)...)
			_v1.POST("/users", append(_createuserMw(), h.CreateUser)...)
		}
	}
}
