// Code generated by hz. DO NOT EDIT.

package asset

import "context"

type AssetService interface {
	ListAssets(ctx context.Context, req *ListAssetsRequest) (*ListAssetsResponse, error)
	CreateAsset(ctx context.Context, req *CreateAssetRequest) (*CreateAssetResponse, error)
	GetAsset(ctx context.Context, req *GetAssetRequest) (*GetAssetResponse, error)
	UpdateAsset(ctx context.Context, req *UpdateAssetRequest) (*UpdateAssetResponse, error)
	DeleteAsset(ctx context.Context, req *DeleteAssetRequest) (*DeleteAssetResponse, error)
}
