// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: app/auth/internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap holds this service's private config only. Shared config
// (service / registry / log) lives in pkg/conf and is scanned separately
// by pkg/bootstrap.
type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Auth          *Auth                  `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_app_auth_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          *Server_GRPC           `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Metrics       *Server_Metrics        `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_app_auth_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetMetrics() *Server_Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserService   *Data_UserService      `protobuf:"bytes,1,opt,name=user_service,json=userService,proto3" json:"user_service,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_app_auth_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetUserService() *Data_UserService {
	if x != nil {
		return x.UserService
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type Auth struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JwtSecret          string                 `protobuf:"bytes,1,opt,name=jwt_secret,json=jwtSecret,proto3" json:"jwt_secret,omitempty"`
	AccessTokenExpiry  int64                  `protobuf:"varint,2,opt,name=access_token_expiry,json=accessTokenExpiry,proto3" json:"access_token_expiry,omitempty"`
	RefreshTokenExpiry int64                  `protobuf:"varint,3,opt,name=refresh_token_expiry,json=refreshTokenExpiry,proto3" json:"refresh_token_expiry,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_app_auth_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Auth) GetJwtSecret() string {
	if x != nil {
		return x.JwtSecret
	}
	return ""
}

func (x *Auth) GetAccessTokenExpiry() int64 {
	if x != nil {
		return x.AccessTokenExpiry
	}
	return 0
}

func (x *Auth) GetRefreshTokenExpiry() int64 {
	if x != nil {
		return x.RefreshTokenExpiry
	}
	return 0
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_app_auth_internal_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_Metrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prometheus /metrics listen address; empty disables the endpoint.
	Addr          string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_Metrics) Reset() {
	*x = Server_Metrics{}
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Metrics) ProtoMessage() {}

func (x *Server_Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_Metrics.ProtoReflect.Descriptor instead.
func (*Server_Metrics) Descriptor() ([]byte, []int) {
	return file_app_auth_internal_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_Metrics) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type Data_UserService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host:port (local) or discovery:///user (via registry)
	Endpoint      string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_UserService) Reset() {
	*x = Data_UserService{}
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_UserService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_UserService) ProtoMessage() {}

func (x *Data_UserService) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_UserService.ProtoReflect.Descriptor instead.
func (*Data_UserService) Descriptor() ([]byte, []int) {
	return file_app_auth_internal_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_UserService) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_internal_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_app_auth_internal_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

var File_app_auth_internal_conf_conf_proto protoreflect.FileDescriptor

const file_app_auth_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	"!app/auth/internal/conf/conf.proto\x12\x14kratos.api.auth.conf\x1a\x1egoogle/protobuf/duration.proto\"\xa1\x01\n" +
	"\tBootstrap\x124\n" +
	"\x06server\x18\x01 \x01(\v2\x1c.kratos.api.auth.conf.ServerR\x06server\x12.\n" +
	"\x04data\x18\x02 \x01(\v2\x1a.kratos.api.auth.conf.DataR\x04data\x12.\n" +
	"\x04auth\x18\x03 \x01(\v2\x1a.kratos.api.auth.conf.AuthR\x04auth\"\xef\x01\n" +
	"\x06Server\x125\n" +
	"\x04grpc\x18\x01 \x01(\v2!.kratos.api.auth.conf.Server.GRPCR\x04grpc\x12>\n" +
	"\ametrics\x18\x02 \x01(\v2$.kratos.api.auth.conf.Server.MetricsR\ametrics\x1aO\n" +
	"\x04GRPC\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1a\x1d\n" +
	"\aMetrics\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"\xfd\x01\n" +
	"\x04Data\x12I\n" +
	"\fuser_service\x18\x01 \x01(\v2&.kratos.api.auth.conf.Data.UserServiceR\vuserService\x126\n" +
	"\x05redis\x18\x02 \x01(\v2 .kratos.api.auth.conf.Data.RedisR\x05redis\x1a)\n" +
	"\vUserService\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x1aG\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\"\x87\x01\n" +
	"\x04Auth\x12\x1d\n" +
	"\n" +
	"jwt_secret\x18\x01 \x01(\tR\tjwtSecret\x12.\n" +
	"\x13access_token_expiry\x18\x02 \x01(\x03R\x11accessTokenExpiry\x120\n" +
	"\x14refresh_token_expiry\x18\x03 \x01(\x03R\x12refreshTokenExpiryB-Z+kratos-template/app/auth/internal/conf;confb\x06proto3"

var (
	file_app_auth_internal_conf_conf_proto_rawDescOnce sync.Once
	file_app_auth_internal_conf_conf_proto_rawDescData []byte
)

func file_app_auth_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_app_auth_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_app_auth_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_auth_internal_conf_conf_proto_rawDesc), len(file_app_auth_internal_conf_conf_proto_rawDesc)))
	})
	return file_app_auth_internal_conf_conf_proto_rawDescData
}

var file_app_auth_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_app_auth_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.auth.conf.Bootstrap
	(*Server)(nil),              // 1: kratos.api.auth.conf.Server
	(*Data)(nil),                // 2: kratos.api.auth.conf.Data
	(*Auth)(nil),                // 3: kratos.api.auth.conf.Auth
	(*Server_GRPC)(nil),         // 4: kratos.api.auth.conf.Server.GRPC
	(*Server_Metrics)(nil),      // 5: kratos.api.auth.conf.Server.Metrics
	(*Data_UserService)(nil),    // 6: kratos.api.auth.conf.Data.UserService
	(*Data_Redis)(nil),          // 7: kratos.api.auth.conf.Data.Redis
	(*durationpb.Duration)(nil), // 8: google.protobuf.Duration
}
var file_app_auth_internal_conf_conf_proto_depIdxs = []int32{
	1, // 0: kratos.api.auth.conf.Bootstrap.server:type_name -> kratos.api.auth.conf.Server
	2, // 1: kratos.api.auth.conf.Bootstrap.data:type_name -> kratos.api.auth.conf.Data
	3, // 2: kratos.api.auth.conf.Bootstrap.auth:type_name -> kratos.api.auth.conf.Auth
	4, // 3: kratos.api.auth.conf.Server.grpc:type_name -> kratos.api.auth.conf.Server.GRPC
	5, // 4: kratos.api.auth.conf.Server.metrics:type_name -> kratos.api.auth.conf.Server.Metrics
	6, // 5: kratos.api.auth.conf.Data.user_service:type_name -> kratos.api.auth.conf.Data.UserService
	7, // 6: kratos.api.auth.conf.Data.redis:type_name -> kratos.api.auth.conf.Data.Redis
	8, // 7: kratos.api.auth.conf.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_app_auth_internal_conf_conf_proto_init() }
func file_app_auth_internal_conf_conf_proto_init() {
	if File_app_auth_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_auth_internal_conf_conf_proto_rawDesc), len(file_app_auth_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_auth_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_app_auth_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_app_auth_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_app_auth_internal_conf_conf_proto = out.File
	file_app_auth_internal_conf_conf_proto_goTypes = nil
	file_app_auth_internal_conf_conf_proto_depIdxs = nil
}
