// Code generated by hz. DO NOT EDIT.

package module

import (
	"go.uber.org/fx"

	"kratos-template/app/gateway/biz/handler"
	assetrouter "kratos-template/app/gateway/biz/router/asset"
	assetservice "kratos-template/app/gateway/internal/service/asset"
)

func init() {
	register(fx.Module("asset",
		fx.Provide(assetservice.NewService, handler.NewAssetHandler),
		fx.Invoke(assetrouter.Register),
	))
}
