// Code generated by hz. DO NOT EDIT.

package module

import (
	"go.uber.org/fx"

	"kratos-template/app/gateway/biz/handler"
	authrouter "kratos-template/app/gateway/biz/router/auth"
	authservice "kratos-template/app/gateway/internal/service/auth"
)

func init() {
	register(fx.Module("auth",
		fx.Provide(authservice.NewService, handler.NewAuthHandler),
		fx.Invoke(authrouter.Register),
	))
}
