// Code generated by hz. DO NOT EDIT.

package module

import (
	"go.uber.org/fx"

	"kratos-template/app/gateway/biz/handler"
	echorouter "kratos-template/app/gateway/biz/router/echo"
	echoservice "kratos-template/app/gateway/internal/service/echo"
)

func init() {
	register(fx.Module("echo",
		fx.Provide(echoservice.NewService, handler.NewEchoHandler),
		fx.Invoke(echorouter.Register),
	))
}
