// Code generated by hz. DO NOT EDIT.

package module

import (
	"go.uber.org/fx"

	"kratos-template/app/gateway/biz/handler"
	userrouter "kratos-template/app/gateway/biz/router/user"
	userservice "kratos-template/app/gateway/internal/service/user"
)

func init() {
	register(fx.Module("user",
		fx.Provide(userservice.NewService, handler.NewUserHandler),
		fx.Invoke(userrouter.Register),
	))
}
