// Code generated by hz. DO NOT EDIT.

package echo

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	"kratos-template/app/gateway/biz/handler"
)

func Register(r *server.Hertz, h *handler.EchoHandler) {
	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_v1 := _api.Group("/v1", _v1Mw()...)
			_v1.POST("/echo", append(_echoMw(), h.Echo)...)
			_v1.GET("/ping", append(_pingMw(), h.Ping)...)
		}
	}
}
