// Code generated by hz. DO NOT EDIT.

package echo

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"go.uber.org/fx"
	"kratos-template/app/gateway/biz/handler"
	echoservice "kratos-template/app/gateway/biz/service/echo"
)

func Register(r map[string]fx.Option) {
	r["echo"] = fx.Module("echo",
		fx.Provide(echoservice.NewService, handler.NewEchoHandler),
		fx.Invoke(RegisterRouter),
	)
}

func RegisterRouter(r *server.Hertz, h *handler.EchoHandler) {
	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_v1 := _api.Group("/v1", _v1Mw()...)
			_v1.GET("/echo", append(_echoMw(), h.Echo)...)
		}
	}
}
