server:
  grpc:
    addr: 0.0.0.0:9082
    timeout: 30s

data:
  database:
    source: postgres://postgres:postgres@postgres:5432/user_db?sslmode=disable
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: 30m

auth:
  jwt_secret: CHANGE_ME

registry:
  consul:
    address: consul:8500
    scheme: http

log:
  level: info
  env: development
