global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: /metrics

  - job_name: 'auth'
    static_configs:
      - targets: ['auth:8081']
    metrics_path: /metrics

  - job_name: 'user'
    static_configs:
      - targets: ['user:8082']
    metrics_path: /metrics

  - job_name: 'asset'
    static_configs:
      - targets: ['asset:8083']
    metrics_path: /metrics

  - job_name: 'worker'
    static_configs:
      - targets: ['worker:8084']
    metrics_path: /metrics

  - job_name: 'consul'
    static_configs:
      - targets: ['consul:8500']
    metrics_path: /v1/agent/metrics
    params:
      format: ['prometheus']
