// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             (unknown)
// source: asset/v1/asset.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAssetServiceCreateAsset = "/api.asset.v1.AssetService/CreateAsset"
const OperationAssetServiceDeleteAsset = "/api.asset.v1.AssetService/DeleteAsset"
const OperationAssetServiceGetAsset = "/api.asset.v1.AssetService/GetAsset"
const OperationAssetServiceListAssets = "/api.asset.v1.AssetService/ListAssets"
const OperationAssetServiceUpdateAsset = "/api.asset.v1.AssetService/UpdateAsset"

type AssetServiceHTTPServer interface {
	CreateAsset(context.Context, *CreateAssetRequest) (*CreateAssetReply, error)
	DeleteAsset(context.Context, *DeleteAssetRequest) (*DeleteAssetReply, error)
	GetAsset(context.Context, *GetAssetRequest) (*GetAssetReply, error)
	ListAssets(context.Context, *ListAssetsRequest) (*ListAssetsReply, error)
	UpdateAsset(context.Context, *UpdateAssetRequest) (*UpdateAssetReply, error)
}

func RegisterAssetServiceHTTPServer(s *http.Server, srv AssetServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/assets", _AssetService_CreateAsset0_HTTP_Handler(srv))
	r.GET("/api/v1/assets/{id}", _AssetService_GetAsset0_HTTP_Handler(srv))
	r.PUT("/api/v1/assets/{id}", _AssetService_UpdateAsset0_HTTP_Handler(srv))
	r.DELETE("/api/v1/assets/{id}", _AssetService_DeleteAsset0_HTTP_Handler(srv))
	r.GET("/api/v1/assets", _AssetService_ListAssets0_HTTP_Handler(srv))
}

func _AssetService_CreateAsset0_HTTP_Handler(srv AssetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAssetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetServiceCreateAsset)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAsset(ctx, req.(*CreateAssetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAssetReply)
		return ctx.Result(200, reply)
	}
}

func _AssetService_GetAsset0_HTTP_Handler(srv AssetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAssetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetServiceGetAsset)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAsset(ctx, req.(*GetAssetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAssetReply)
		return ctx.Result(200, reply)
	}
}

func _AssetService_UpdateAsset0_HTTP_Handler(srv AssetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAssetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetServiceUpdateAsset)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAsset(ctx, req.(*UpdateAssetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateAssetReply)
		return ctx.Result(200, reply)
	}
}

func _AssetService_DeleteAsset0_HTTP_Handler(srv AssetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAssetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetServiceDeleteAsset)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteAsset(ctx, req.(*DeleteAssetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteAssetReply)
		return ctx.Result(200, reply)
	}
}

func _AssetService_ListAssets0_HTTP_Handler(srv AssetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAssetsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetServiceListAssets)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAssets(ctx, req.(*ListAssetsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAssetsReply)
		return ctx.Result(200, reply)
	}
}

type AssetServiceHTTPClient interface {
	CreateAsset(ctx context.Context, req *CreateAssetRequest, opts ...http.CallOption) (rsp *CreateAssetReply, err error)
	DeleteAsset(ctx context.Context, req *DeleteAssetRequest, opts ...http.CallOption) (rsp *DeleteAssetReply, err error)
	GetAsset(ctx context.Context, req *GetAssetRequest, opts ...http.CallOption) (rsp *GetAssetReply, err error)
	ListAssets(ctx context.Context, req *ListAssetsRequest, opts ...http.CallOption) (rsp *ListAssetsReply, err error)
	UpdateAsset(ctx context.Context, req *UpdateAssetRequest, opts ...http.CallOption) (rsp *UpdateAssetReply, err error)
}

type AssetServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAssetServiceHTTPClient(client *http.Client) AssetServiceHTTPClient {
	return &AssetServiceHTTPClientImpl{client}
}

func (c *AssetServiceHTTPClientImpl) CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...http.CallOption) (*CreateAssetReply, error) {
	var out CreateAssetReply
	pattern := "/api/v1/assets"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAssetServiceCreateAsset))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AssetServiceHTTPClientImpl) DeleteAsset(ctx context.Context, in *DeleteAssetRequest, opts ...http.CallOption) (*DeleteAssetReply, error) {
	var out DeleteAssetReply
	pattern := "/api/v1/assets/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAssetServiceDeleteAsset))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AssetServiceHTTPClientImpl) GetAsset(ctx context.Context, in *GetAssetRequest, opts ...http.CallOption) (*GetAssetReply, error) {
	var out GetAssetReply
	pattern := "/api/v1/assets/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAssetServiceGetAsset))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AssetServiceHTTPClientImpl) ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...http.CallOption) (*ListAssetsReply, error) {
	var out ListAssetsReply
	pattern := "/api/v1/assets"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAssetServiceListAssets))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AssetServiceHTTPClientImpl) UpdateAsset(ctx context.Context, in *UpdateAssetRequest, opts ...http.CallOption) (*UpdateAssetReply, error) {
	var out UpdateAssetReply
	pattern := "/api/v1/assets/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAssetServiceUpdateAsset))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
