// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: asset/v1/asset.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Value         float64                `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_asset_v1_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_asset_v1_asset_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Asset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Asset) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Asset) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Asset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Asset) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssetRequest) Reset() {
	*x = CreateAssetRequest{}
	mi := &file_asset_v1_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetRequest) ProtoMessage() {}

func (x *CreateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetRequest.ProtoReflect.Descriptor instead.
func (*CreateAssetRequest) Descriptor() ([]byte, []int) {
	return file_asset_v1_asset_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAssetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAssetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAssetRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateAssetRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type CreateAssetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssetReply) Reset() {
	*x = CreateAssetReply{}
	mi := &file_asset_v1_asset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetReply) ProtoMessage() {}

func (x *CreateAssetReply) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_asset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetReply.ProtoReflect.Descriptor instead.
func (*CreateAssetReply) Descriptor() ([]byte, []int) {
	return file_asset_v1_asset_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAssetReply) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type GetAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	mi := &file_asset_v1_asset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_asset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_asset_v1_asset_proto_rawDescGZIP(), []int{3}
}

func (x *GetAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAssetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetReply) Reset() {
	*x = GetAssetReply{}
	mi := &file_asset_v1_asset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetReply) ProtoMessage() {}

func (x *GetAssetReply) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_asset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetReply.ProtoReflect.Descriptor instead.
func (*GetAssetReply) Descriptor() ([]byte, []int) {
	return file_asset_v1_asset_proto_rawDescGZIP(), []int{4}
}

func (x *GetAssetReply) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type UpdateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetRequest) Reset() {
	*x = UpdateAssetRequest{}
	mi := &file_asset_v1_asset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetRequest) ProtoMessage() {}

func (x *UpdateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_asset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssetRequest) Descriptor() ([]byte, []int) {
	return file_asset_v1_asset_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAssetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAssetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAssetRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateAssetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetReply) Reset() {
	*x = UpdateAssetReply{}
	mi := &file_asset_v1_asset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetReply) ProtoMessage() {}

func (x *UpdateAssetReply) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_asset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetReply.ProtoReflect.Descriptor instead.
func (*UpdateAssetReply) Descriptor() ([]byte, []int) {
	return file_asset_v1_asset_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAssetReply) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type DeleteAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssetRequest) Reset() {
	*x = DeleteAssetRequest{}
	mi := &file_asset_v1_asset_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssetRequest) ProtoMessage() {}

func (x *DeleteAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_asset_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssetRequest.ProtoReflect.Descriptor instead.
func (*DeleteAssetRequest) Descriptor() ([]byte, []int) {
	return file_asset_v1_asset_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAssetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssetReply) Reset() {
	*x = DeleteAssetReply{}
	mi := &file_asset_v1_asset_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssetReply) ProtoMessage() {}

func (x *DeleteAssetReply) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_asset_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssetReply.ProtoReflect.Descriptor instead.
func (*DeleteAssetReply) Descriptor() ([]byte, []int) {
	return file_asset_v1_asset_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAssetReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsRequest) Reset() {
	*x = ListAssetsRequest{}
	mi := &file_asset_v1_asset_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsRequest) ProtoMessage() {}

func (x *ListAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_asset_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsRequest) Descriptor() ([]byte, []int) {
	return file_asset_v1_asset_proto_rawDescGZIP(), []int{9}
}

func (x *ListAssetsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAssetsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAssetsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type ListAssetsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsReply) Reset() {
	*x = ListAssetsReply{}
	mi := &file_asset_v1_asset_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsReply) ProtoMessage() {}

func (x *ListAssetsReply) ProtoReflect() protoreflect.Message {
	mi := &file_asset_v1_asset_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsReply.ProtoReflect.Descriptor instead.
func (*ListAssetsReply) Descriptor() ([]byte, []int) {
	return file_asset_v1_asset_proto_rawDescGZIP(), []int{10}
}

func (x *ListAssetsReply) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *ListAssetsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_asset_v1_asset_proto protoreflect.FileDescriptor

const file_asset_v1_asset_proto_rawDesc = "" +
	"\n" +
	"\x14asset/v1/asset.proto\x12\fapi.asset.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x01\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"{\n" +
	"\x12CreateAssetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\"=\n" +
	"\x10CreateAssetReply\x12)\n" +
	"\x05asset\x18\x01 \x01(\v2\x13.api.asset.v1.AssetR\x05asset\"!\n" +
	"\x0fGetAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\rGetAssetReply\x12)\n" +
	"\x05asset\x18\x01 \x01(\v2\x13.api.asset.v1.AssetR\x05asset\"p\n" +
	"\x12UpdateAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\"=\n" +
	"\x10UpdateAssetReply\x12)\n" +
	"\x05asset\x18\x01 \x01(\v2\x13.api.asset.v1.AssetR\x05asset\"$\n" +
	"\x12DeleteAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x10DeleteAssetReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"_\n" +
	"\x11ListAssetsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\"T\n" +
	"\x0fListAssetsReply\x12+\n" +
	"\x06assets\x18\x01 \x03(\v2\x13.api.asset.v1.AssetR\x06assets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xa4\x04\n" +
	"\fAssetService\x12j\n" +
	"\vCreateAsset\x12 .api.asset.v1.CreateAssetRequest\x1a\x1e.api.asset.v1.CreateAssetReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/assets\x12c\n" +
	"\bGetAsset\x12\x1d.api.asset.v1.GetAssetRequest\x1a\x1b.api.asset.v1.GetAssetReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/assets/{id}\x12o\n" +
	"\vUpdateAsset\x12 .api.asset.v1.UpdateAssetRequest\x1a\x1e.api.asset.v1.UpdateAssetReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/api/v1/assets/{id}\x12l\n" +
	"\vDeleteAsset\x12 .api.asset.v1.DeleteAssetRequest\x1a\x1e.api.asset.v1.DeleteAssetReply\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/v1/assets/{id}\x12d\n" +
	"\n" +
	"ListAssets\x12\x1f.api.asset.v1.ListAssetsRequest\x1a\x1d.api.asset.v1.ListAssetsReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/assetsB!Z\x1fkratos-template/api/asset/v1;v1b\x06proto3"

var (
	file_asset_v1_asset_proto_rawDescOnce sync.Once
	file_asset_v1_asset_proto_rawDescData []byte
)

func file_asset_v1_asset_proto_rawDescGZIP() []byte {
	file_asset_v1_asset_proto_rawDescOnce.Do(func() {
		file_asset_v1_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asset_v1_asset_proto_rawDesc), len(file_asset_v1_asset_proto_rawDesc)))
	})
	return file_asset_v1_asset_proto_rawDescData
}

var file_asset_v1_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_asset_v1_asset_proto_goTypes = []any{
	(*Asset)(nil),                 // 0: api.asset.v1.Asset
	(*CreateAssetRequest)(nil),    // 1: api.asset.v1.CreateAssetRequest
	(*CreateAssetReply)(nil),      // 2: api.asset.v1.CreateAssetReply
	(*GetAssetRequest)(nil),       // 3: api.asset.v1.GetAssetRequest
	(*GetAssetReply)(nil),         // 4: api.asset.v1.GetAssetReply
	(*UpdateAssetRequest)(nil),    // 5: api.asset.v1.UpdateAssetRequest
	(*UpdateAssetReply)(nil),      // 6: api.asset.v1.UpdateAssetReply
	(*DeleteAssetRequest)(nil),    // 7: api.asset.v1.DeleteAssetRequest
	(*DeleteAssetReply)(nil),      // 8: api.asset.v1.DeleteAssetReply
	(*ListAssetsRequest)(nil),     // 9: api.asset.v1.ListAssetsRequest
	(*ListAssetsReply)(nil),       // 10: api.asset.v1.ListAssetsReply
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_asset_v1_asset_proto_depIdxs = []int32{
	11, // 0: api.asset.v1.Asset.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: api.asset.v1.Asset.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: api.asset.v1.CreateAssetReply.asset:type_name -> api.asset.v1.Asset
	0,  // 3: api.asset.v1.GetAssetReply.asset:type_name -> api.asset.v1.Asset
	0,  // 4: api.asset.v1.UpdateAssetReply.asset:type_name -> api.asset.v1.Asset
	0,  // 5: api.asset.v1.ListAssetsReply.assets:type_name -> api.asset.v1.Asset
	1,  // 6: api.asset.v1.AssetService.CreateAsset:input_type -> api.asset.v1.CreateAssetRequest
	3,  // 7: api.asset.v1.AssetService.GetAsset:input_type -> api.asset.v1.GetAssetRequest
	5,  // 8: api.asset.v1.AssetService.UpdateAsset:input_type -> api.asset.v1.UpdateAssetRequest
	7,  // 9: api.asset.v1.AssetService.DeleteAsset:input_type -> api.asset.v1.DeleteAssetRequest
	9,  // 10: api.asset.v1.AssetService.ListAssets:input_type -> api.asset.v1.ListAssetsRequest
	2,  // 11: api.asset.v1.AssetService.CreateAsset:output_type -> api.asset.v1.CreateAssetReply
	4,  // 12: api.asset.v1.AssetService.GetAsset:output_type -> api.asset.v1.GetAssetReply
	6,  // 13: api.asset.v1.AssetService.UpdateAsset:output_type -> api.asset.v1.UpdateAssetReply
	8,  // 14: api.asset.v1.AssetService.DeleteAsset:output_type -> api.asset.v1.DeleteAssetReply
	10, // 15: api.asset.v1.AssetService.ListAssets:output_type -> api.asset.v1.ListAssetsReply
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_asset_v1_asset_proto_init() }
func file_asset_v1_asset_proto_init() {
	if File_asset_v1_asset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asset_v1_asset_proto_rawDesc), len(file_asset_v1_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asset_v1_asset_proto_goTypes,
		DependencyIndexes: file_asset_v1_asset_proto_depIdxs,
		MessageInfos:      file_asset_v1_asset_proto_msgTypes,
	}.Build()
	File_asset_v1_asset_proto = out.File
	file_asset_v1_asset_proto_goTypes = nil
	file_asset_v1_asset_proto_depIdxs = nil
}
