// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kratos-template/pkg/model"
)

func newAsset(db *gorm.DB, opts ...gen.DOOption) asset {
	_asset := asset{}

	_asset.assetDo.UseDB(db, opts...)
	_asset.assetDo.UseModel(&model.Asset{})

	tableName := _asset.assetDo.TableName()
	_asset.ALL = field.NewAsterisk(tableName)
	_asset.ID = field.NewString(tableName, "id")
	_asset.Name = field.NewString(tableName, "name")
	_asset.Description = field.NewString(tableName, "description")
	_asset.OwnerID = field.NewString(tableName, "owner_id")
	_asset.Value = field.NewFloat64(tableName, "value")
	_asset.CreatedAt = field.NewTime(tableName, "created_at")
	_asset.UpdatedAt = field.NewTime(tableName, "updated_at")

	_asset.fillFieldMap()

	return _asset
}

type asset struct {
	assetDo

	ALL         field.Asterisk
	ID          field.String
	Name        field.String
	Description field.String
	OwnerID     field.String
	Value       field.Float64
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (a asset) Table(newTableName string) *asset {
	a.assetDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a asset) As(alias string) *asset {
	a.assetDo.DO = *(a.assetDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *asset) updateTableName(table string) *asset {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.Name = field.NewString(table, "name")
	a.Description = field.NewString(table, "description")
	a.OwnerID = field.NewString(table, "owner_id")
	a.Value = field.NewFloat64(table, "value")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *asset) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *asset) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 7)
	a.fieldMap["id"] = a.ID
	a.fieldMap["name"] = a.Name
	a.fieldMap["description"] = a.Description
	a.fieldMap["owner_id"] = a.OwnerID
	a.fieldMap["value"] = a.Value
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a asset) clone(db *gorm.DB) asset {
	a.assetDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a asset) replaceDB(db *gorm.DB) asset {
	a.assetDo.ReplaceDB(db)
	return a
}

type assetDo struct{ gen.DO }

type IAssetDo interface {
	gen.SubQuery
	Debug() IAssetDo
	WithContext(ctx context.Context) IAssetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAssetDo
	WriteDB() IAssetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAssetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAssetDo
	Not(conds ...gen.Condition) IAssetDo
	Or(conds ...gen.Condition) IAssetDo
	Select(conds ...field.Expr) IAssetDo
	Where(conds ...gen.Condition) IAssetDo
	Order(conds ...field.Expr) IAssetDo
	Distinct(cols ...field.Expr) IAssetDo
	Omit(cols ...field.Expr) IAssetDo
	Join(table schema.Tabler, on ...field.Expr) IAssetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAssetDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAssetDo
	Group(cols ...field.Expr) IAssetDo
	Having(conds ...gen.Condition) IAssetDo
	Limit(limit int) IAssetDo
	Offset(offset int) IAssetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAssetDo
	Unscoped() IAssetDo
	Create(values ...*model.Asset) error
	CreateInBatches(values []*model.Asset, batchSize int) error
	Save(values ...*model.Asset) error
	First() (*model.Asset, error)
	Take() (*model.Asset, error)
	Last() (*model.Asset, error)
	Find() ([]*model.Asset, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Asset, err error)
	FindInBatches(result *[]*model.Asset, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Asset) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAssetDo
	Assign(attrs ...field.AssignExpr) IAssetDo
	Joins(fields ...field.RelationField) IAssetDo
	Preload(fields ...field.RelationField) IAssetDo
	FirstOrInit() (*model.Asset, error)
	FirstOrCreate() (*model.Asset, error)
	FindByPage(offset int, limit int) (result []*model.Asset, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAssetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a assetDo) Debug() IAssetDo {
	return a.withDO(a.DO.Debug())
}

func (a assetDo) WithContext(ctx context.Context) IAssetDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a assetDo) ReadDB() IAssetDo {
	return a.Clauses(dbresolver.Read)
}

func (a assetDo) WriteDB() IAssetDo {
	return a.Clauses(dbresolver.Write)
}

func (a assetDo) Session(config *gorm.Session) IAssetDo {
	return a.withDO(a.DO.Session(config))
}

func (a assetDo) Clauses(conds ...clause.Expression) IAssetDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a assetDo) Returning(value interface{}, columns ...string) IAssetDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a assetDo) Not(conds ...gen.Condition) IAssetDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a assetDo) Or(conds ...gen.Condition) IAssetDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a assetDo) Select(conds ...field.Expr) IAssetDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a assetDo) Where(conds ...gen.Condition) IAssetDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a assetDo) Order(conds ...field.Expr) IAssetDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a assetDo) Distinct(cols ...field.Expr) IAssetDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a assetDo) Omit(cols ...field.Expr) IAssetDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a assetDo) Join(table schema.Tabler, on ...field.Expr) IAssetDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a assetDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAssetDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a assetDo) RightJoin(table schema.Tabler, on ...field.Expr) IAssetDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a assetDo) Group(cols ...field.Expr) IAssetDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a assetDo) Having(conds ...gen.Condition) IAssetDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a assetDo) Limit(limit int) IAssetDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a assetDo) Offset(offset int) IAssetDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a assetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAssetDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a assetDo) Unscoped() IAssetDo {
	return a.withDO(a.DO.Unscoped())
}

func (a assetDo) Create(values ...*model.Asset) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a assetDo) CreateInBatches(values []*model.Asset, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a assetDo) Save(values ...*model.Asset) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a assetDo) First() (*model.Asset, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Asset), nil
	}
}

func (a assetDo) Take() (*model.Asset, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Asset), nil
	}
}

func (a assetDo) Last() (*model.Asset, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Asset), nil
	}
}

func (a assetDo) Find() ([]*model.Asset, error) {
	result, err := a.DO.Find()
	return result.([]*model.Asset), err
}

func (a assetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Asset, err error) {
	buf := make([]*model.Asset, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a assetDo) FindInBatches(result *[]*model.Asset, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a assetDo) Attrs(attrs ...field.AssignExpr) IAssetDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a assetDo) Assign(attrs ...field.AssignExpr) IAssetDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a assetDo) Joins(fields ...field.RelationField) IAssetDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a assetDo) Preload(fields ...field.RelationField) IAssetDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a assetDo) FirstOrInit() (*model.Asset, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Asset), nil
	}
}

func (a assetDo) FirstOrCreate() (*model.Asset, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Asset), nil
	}
}

func (a assetDo) FindByPage(offset int, limit int) (result []*model.Asset, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a assetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a assetDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a assetDo) Delete(models ...*model.Asset) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *assetDo) withDO(do gen.Dao) *assetDo {
	a.DO = *do.(*gen.DO)
	return a
}
