// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: app/gateway/internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Client        *Client                `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Temporal      *Temporal              `protobuf:"bytes,3,opt,name=temporal,proto3" json:"temporal,omitempty"`
	Service       *Service               `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Registry      *Registry              `protobuf:"bytes,5,opt,name=registry,proto3" json:"registry,omitempty"`
	Tracing       *Tracing               `protobuf:"bytes,6,opt,name=tracing,proto3" json:"tracing,omitempty"`
	Log           *Log                   `protobuf:"bytes,7,opt,name=log,proto3" json:"log,omitempty"`
	Auth          *Auth                  `protobuf:"bytes,8,opt,name=auth,proto3" json:"auth,omitempty"`
	RateLimit     *RateLimit             `protobuf:"bytes,9,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *Bootstrap) GetTemporal() *Temporal {
	if x != nil {
		return x.Temporal
	}
	return nil
}

func (x *Bootstrap) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Bootstrap) GetRegistry() *Registry {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *Bootstrap) GetTracing() *Tracing {
	if x != nil {
		return x.Tracing
	}
	return nil
}

func (x *Bootstrap) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Bootstrap) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Bootstrap) GetRateLimit() *RateLimit {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Client_Endpoint       `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	User          *Client_Endpoint       `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Asset         *Client_Endpoint       `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Client) GetAuth() *Client_Endpoint {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Client) GetUser() *Client_Endpoint {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Client) GetAsset() *Client_Endpoint {
	if x != nil {
		return x.Asset
	}
	return nil
}

type Temporal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPort      string                 `protobuf:"bytes,1,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Temporal) Reset() {
	*x = Temporal{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Temporal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temporal) ProtoMessage() {}

func (x *Temporal) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temporal.ProtoReflect.Descriptor instead.
func (*Temporal) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Temporal) GetHostPort() string {
	if x != nil {
		return x.HostPort
	}
	return ""
}

func (x *Temporal) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Registry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consul        *Registry_Consul       `protobuf:"bytes,1,opt,name=consul,proto3" json:"consul,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Registry) GetConsul() *Registry_Consul {
	if x != nil {
		return x.Consul
	}
	return nil
}

type Tracing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Otlp          *Tracing_Otlp          `protobuf:"bytes,1,opt,name=otlp,proto3" json:"otlp,omitempty"`
	SampleRate    float64                `protobuf:"fixed64,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tracing) Reset() {
	*x = Tracing{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracing) ProtoMessage() {}

func (x *Tracing) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracing.ProtoReflect.Descriptor instead.
func (*Tracing) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Tracing) GetOtlp() *Tracing_Otlp {
	if x != nil {
		return x.Otlp
	}
	return nil
}

func (x *Tracing) GetSampleRate() float64 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtSecret     string                 `protobuf:"bytes,1,opt,name=jwt_secret,json=jwtSecret,proto3" json:"jwt_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *Auth) GetJwtSecret() string {
	if x != nil {
		return x.JwtSecret
	}
	return ""
}

type RateLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      int64                  `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Rate          int64                  `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimit) Reset() {
	*x = RateLimit{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimit) ProtoMessage() {}

func (x *RateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimit.ProtoReflect.Descriptor instead.
func (*RateLimit) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{9}
}

func (x *RateLimit) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *RateLimit) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       string                 `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type Client_Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiscoveryName string                 `protobuf:"bytes,1,opt,name=discovery_name,json=discoveryName,proto3" json:"discovery_name,omitempty"`
	Timeout       string                 `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client_Endpoint) Reset() {
	*x = Client_Endpoint{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client_Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_Endpoint) ProtoMessage() {}

func (x *Client_Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_Endpoint.ProtoReflect.Descriptor instead.
func (*Client_Endpoint) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Client_Endpoint) GetDiscoveryName() string {
	if x != nil {
		return x.DiscoveryName
	}
	return ""
}

func (x *Client_Endpoint) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type Registry_Consul struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Scheme        string                 `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry_Consul) Reset() {
	*x = Registry_Consul{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry_Consul) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry_Consul) ProtoMessage() {}

func (x *Registry_Consul) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry_Consul.ProtoReflect.Descriptor instead.
func (*Registry_Consul) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Registry_Consul) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Registry_Consul) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

type Tracing_Otlp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tracing_Otlp) Reset() {
	*x = Tracing_Otlp{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracing_Otlp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracing_Otlp) ProtoMessage() {}

func (x *Tracing_Otlp) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracing_Otlp.ProtoReflect.Descriptor instead.
func (*Tracing_Otlp) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Tracing_Otlp) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

var File_app_gateway_internal_conf_conf_proto protoreflect.FileDescriptor

const file_app_gateway_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	"$app/gateway/internal/conf/conf.proto\x12\x17kratos.api.gateway.conf\"\x99\x04\n" +
	"\tBootstrap\x127\n" +
	"\x06server\x18\x01 \x01(\v2\x1f.kratos.api.gateway.conf.ServerR\x06server\x127\n" +
	"\x06client\x18\x02 \x01(\v2\x1f.kratos.api.gateway.conf.ClientR\x06client\x12=\n" +
	"\btemporal\x18\x03 \x01(\v2!.kratos.api.gateway.conf.TemporalR\btemporal\x12:\n" +
	"\aservice\x18\x04 \x01(\v2 .kratos.api.gateway.conf.ServiceR\aservice\x12=\n" +
	"\bregistry\x18\x05 \x01(\v2!.kratos.api.gateway.conf.RegistryR\bregistry\x12:\n" +
	"\atracing\x18\x06 \x01(\v2 .kratos.api.gateway.conf.TracingR\atracing\x12.\n" +
	"\x03log\x18\a \x01(\v2\x1c.kratos.api.gateway.conf.LogR\x03log\x121\n" +
	"\x04auth\x18\b \x01(\v2\x1d.kratos.api.gateway.conf.AuthR\x04auth\x12A\n" +
	"\n" +
	"rate_limit\x18\t \x01(\v2\".kratos.api.gateway.conf.RateLimitR\trateLimit\"x\n" +
	"\x06Server\x128\n" +
	"\x04http\x18\x01 \x01(\v2$.kratos.api.gateway.conf.Server.HTTPR\x04http\x1a4\n" +
	"\x04HTTP\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\"\x91\x02\n" +
	"\x06Client\x12<\n" +
	"\x04auth\x18\x01 \x01(\v2(.kratos.api.gateway.conf.Client.EndpointR\x04auth\x12<\n" +
	"\x04user\x18\x02 \x01(\v2(.kratos.api.gateway.conf.Client.EndpointR\x04user\x12>\n" +
	"\x05asset\x18\x03 \x01(\v2(.kratos.api.gateway.conf.Client.EndpointR\x05asset\x1aK\n" +
	"\bEndpoint\x12%\n" +
	"\x0ediscovery_name\x18\x01 \x01(\tR\rdiscoveryName\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\"E\n" +
	"\bTemporal\x12\x1b\n" +
	"\thost_port\x18\x01 \x01(\tR\bhostPort\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"7\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x88\x01\n" +
	"\bRegistry\x12@\n" +
	"\x06consul\x18\x01 \x01(\v2(.kratos.api.gateway.conf.Registry.ConsulR\x06consul\x1a:\n" +
	"\x06Consul\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06scheme\x18\x02 \x01(\tR\x06scheme\"\x89\x01\n" +
	"\aTracing\x129\n" +
	"\x04otlp\x18\x01 \x01(\v2%.kratos.api.gateway.conf.Tracing.OtlpR\x04otlp\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x01R\n" +
	"sampleRate\x1a\"\n" +
	"\x04Otlp\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\"-\n" +
	"\x03Log\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\"%\n" +
	"\x04Auth\x12\x1d\n" +
	"\n" +
	"jwt_secret\x18\x01 \x01(\tR\tjwtSecret\";\n" +
	"\tRateLimit\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x03R\bcapacity\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x03R\x04rateB0Z.kratos-template/app/gateway/internal/conf;confb\x06proto3"

var (
	file_app_gateway_internal_conf_conf_proto_rawDescOnce sync.Once
	file_app_gateway_internal_conf_conf_proto_rawDescData []byte
)

func file_app_gateway_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_app_gateway_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_app_gateway_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_gateway_internal_conf_conf_proto_rawDesc), len(file_app_gateway_internal_conf_conf_proto_rawDesc)))
	})
	return file_app_gateway_internal_conf_conf_proto_rawDescData
}

var file_app_gateway_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_app_gateway_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),       // 0: kratos.api.gateway.conf.Bootstrap
	(*Server)(nil),          // 1: kratos.api.gateway.conf.Server
	(*Client)(nil),          // 2: kratos.api.gateway.conf.Client
	(*Temporal)(nil),        // 3: kratos.api.gateway.conf.Temporal
	(*Service)(nil),         // 4: kratos.api.gateway.conf.Service
	(*Registry)(nil),        // 5: kratos.api.gateway.conf.Registry
	(*Tracing)(nil),         // 6: kratos.api.gateway.conf.Tracing
	(*Log)(nil),             // 7: kratos.api.gateway.conf.Log
	(*Auth)(nil),            // 8: kratos.api.gateway.conf.Auth
	(*RateLimit)(nil),       // 9: kratos.api.gateway.conf.RateLimit
	(*Server_HTTP)(nil),     // 10: kratos.api.gateway.conf.Server.HTTP
	(*Client_Endpoint)(nil), // 11: kratos.api.gateway.conf.Client.Endpoint
	(*Registry_Consul)(nil), // 12: kratos.api.gateway.conf.Registry.Consul
	(*Tracing_Otlp)(nil),    // 13: kratos.api.gateway.conf.Tracing.Otlp
}
var file_app_gateway_internal_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.gateway.conf.Bootstrap.server:type_name -> kratos.api.gateway.conf.Server
	2,  // 1: kratos.api.gateway.conf.Bootstrap.client:type_name -> kratos.api.gateway.conf.Client
	3,  // 2: kratos.api.gateway.conf.Bootstrap.temporal:type_name -> kratos.api.gateway.conf.Temporal
	4,  // 3: kratos.api.gateway.conf.Bootstrap.service:type_name -> kratos.api.gateway.conf.Service
	5,  // 4: kratos.api.gateway.conf.Bootstrap.registry:type_name -> kratos.api.gateway.conf.Registry
	6,  // 5: kratos.api.gateway.conf.Bootstrap.tracing:type_name -> kratos.api.gateway.conf.Tracing
	7,  // 6: kratos.api.gateway.conf.Bootstrap.log:type_name -> kratos.api.gateway.conf.Log
	8,  // 7: kratos.api.gateway.conf.Bootstrap.auth:type_name -> kratos.api.gateway.conf.Auth
	9,  // 8: kratos.api.gateway.conf.Bootstrap.rate_limit:type_name -> kratos.api.gateway.conf.RateLimit
	10, // 9: kratos.api.gateway.conf.Server.http:type_name -> kratos.api.gateway.conf.Server.HTTP
	11, // 10: kratos.api.gateway.conf.Client.auth:type_name -> kratos.api.gateway.conf.Client.Endpoint
	11, // 11: kratos.api.gateway.conf.Client.user:type_name -> kratos.api.gateway.conf.Client.Endpoint
	11, // 12: kratos.api.gateway.conf.Client.asset:type_name -> kratos.api.gateway.conf.Client.Endpoint
	12, // 13: kratos.api.gateway.conf.Registry.consul:type_name -> kratos.api.gateway.conf.Registry.Consul
	13, // 14: kratos.api.gateway.conf.Tracing.otlp:type_name -> kratos.api.gateway.conf.Tracing.Otlp
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_app_gateway_internal_conf_conf_proto_init() }
func file_app_gateway_internal_conf_conf_proto_init() {
	if File_app_gateway_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_gateway_internal_conf_conf_proto_rawDesc), len(file_app_gateway_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_gateway_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_app_gateway_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_app_gateway_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_app_gateway_internal_conf_conf_proto = out.File
	file_app_gateway_internal_conf_conf_proto_goTypes = nil
	file_app_gateway_internal_conf_conf_proto_depIdxs = nil
}
