// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: app/gateway/internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	conf "kratos-template/pkg/conf"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Client        *Client                `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Service       *conf.Service          `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Registry      *conf.Registry         `protobuf:"bytes,5,opt,name=registry,proto3" json:"registry,omitempty"`
	Log           *conf.Log              `protobuf:"bytes,7,opt,name=log,proto3" json:"log,omitempty"`
	Auth          *Auth                  `protobuf:"bytes,8,opt,name=auth,proto3" json:"auth,omitempty"`
	RateLimit     *RateLimit             `protobuf:"bytes,9,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *Bootstrap) GetService() *conf.Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Bootstrap) GetRegistry() *conf.Registry {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *Bootstrap) GetLog() *conf.Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Bootstrap) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Bootstrap) GetRateLimit() *RateLimit {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Client_Endpoint       `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	User          *Client_Endpoint       `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Client) GetAuth() *Client_Endpoint {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Client) GetUser() *Client_Endpoint {
	if x != nil {
		return x.User
	}
	return nil
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtSecret     string                 `protobuf:"bytes,1,opt,name=jwt_secret,json=jwtSecret,proto3" json:"jwt_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Auth) GetJwtSecret() string {
	if x != nil {
		return x.JwtSecret
	}
	return ""
}

type RateLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      int64                  `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Rate          int64                  `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimit) Reset() {
	*x = RateLimit{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimit) ProtoMessage() {}

func (x *RateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimit.ProtoReflect.Descriptor instead.
func (*RateLimit) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *RateLimit) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *RateLimit) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       string                 `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type Client_Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiscoveryName string                 `protobuf:"bytes,1,opt,name=discovery_name,json=discoveryName,proto3" json:"discovery_name,omitempty"`
	Timeout       string                 `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client_Endpoint) Reset() {
	*x = Client_Endpoint{}
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client_Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_Endpoint) ProtoMessage() {}

func (x *Client_Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_internal_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_Endpoint.ProtoReflect.Descriptor instead.
func (*Client_Endpoint) Descriptor() ([]byte, []int) {
	return file_app_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Client_Endpoint) GetDiscoveryName() string {
	if x != nil {
		return x.DiscoveryName
	}
	return ""
}

func (x *Client_Endpoint) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

var File_app_gateway_internal_conf_conf_proto protoreflect.FileDescriptor

const file_app_gateway_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	"$app/gateway/internal/conf/conf.proto\x12\x17kratos.api.gateway.conf\x1a\x13pkg/conf/conf.proto\"\xfa\x02\n" +
	"\tBootstrap\x127\n" +
	"\x06server\x18\x01 \x01(\v2\x1f.kratos.api.gateway.conf.ServerR\x06server\x127\n" +
	"\x06client\x18\x02 \x01(\v2\x1f.kratos.api.gateway.conf.ClientR\x06client\x12.\n" +
	"\aservice\x18\x04 \x01(\v2\x14.kratos.conf.ServiceR\aservice\x121\n" +
	"\bregistry\x18\x05 \x01(\v2\x15.kratos.conf.RegistryR\bregistry\x12\"\n" +
	"\x03log\x18\a \x01(\v2\x10.kratos.conf.LogR\x03log\x121\n" +
	"\x04auth\x18\b \x01(\v2\x1d.kratos.api.gateway.conf.AuthR\x04auth\x12A\n" +
	"\n" +
	"rate_limit\x18\t \x01(\v2\".kratos.api.gateway.conf.RateLimitR\trateLimit\"x\n" +
	"\x06Server\x128\n" +
	"\x04http\x18\x01 \x01(\v2$.kratos.api.gateway.conf.Server.HTTPR\x04http\x1a4\n" +
	"\x04HTTP\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\"\xd1\x01\n" +
	"\x06Client\x12<\n" +
	"\x04auth\x18\x01 \x01(\v2(.kratos.api.gateway.conf.Client.EndpointR\x04auth\x12<\n" +
	"\x04user\x18\x02 \x01(\v2(.kratos.api.gateway.conf.Client.EndpointR\x04user\x1aK\n" +
	"\bEndpoint\x12%\n" +
	"\x0ediscovery_name\x18\x01 \x01(\tR\rdiscoveryName\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\"%\n" +
	"\x04Auth\x12\x1d\n" +
	"\n" +
	"jwt_secret\x18\x01 \x01(\tR\tjwtSecret\";\n" +
	"\tRateLimit\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x03R\bcapacity\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x03R\x04rateB0Z.kratos-template/app/gateway/internal/conf;confb\x06proto3"

var (
	file_app_gateway_internal_conf_conf_proto_rawDescOnce sync.Once
	file_app_gateway_internal_conf_conf_proto_rawDescData []byte
)

func file_app_gateway_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_app_gateway_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_app_gateway_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_gateway_internal_conf_conf_proto_rawDesc), len(file_app_gateway_internal_conf_conf_proto_rawDesc)))
	})
	return file_app_gateway_internal_conf_conf_proto_rawDescData
}

var file_app_gateway_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_app_gateway_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),       // 0: kratos.api.gateway.conf.Bootstrap
	(*Server)(nil),          // 1: kratos.api.gateway.conf.Server
	(*Client)(nil),          // 2: kratos.api.gateway.conf.Client
	(*Auth)(nil),            // 3: kratos.api.gateway.conf.Auth
	(*RateLimit)(nil),       // 4: kratos.api.gateway.conf.RateLimit
	(*Server_HTTP)(nil),     // 5: kratos.api.gateway.conf.Server.HTTP
	(*Client_Endpoint)(nil), // 6: kratos.api.gateway.conf.Client.Endpoint
	(*conf.Service)(nil),    // 7: kratos.conf.Service
	(*conf.Registry)(nil),   // 8: kratos.conf.Registry
	(*conf.Log)(nil),        // 9: kratos.conf.Log
}
var file_app_gateway_internal_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.gateway.conf.Bootstrap.server:type_name -> kratos.api.gateway.conf.Server
	2,  // 1: kratos.api.gateway.conf.Bootstrap.client:type_name -> kratos.api.gateway.conf.Client
	7,  // 2: kratos.api.gateway.conf.Bootstrap.service:type_name -> kratos.conf.Service
	8,  // 3: kratos.api.gateway.conf.Bootstrap.registry:type_name -> kratos.conf.Registry
	9,  // 4: kratos.api.gateway.conf.Bootstrap.log:type_name -> kratos.conf.Log
	3,  // 5: kratos.api.gateway.conf.Bootstrap.auth:type_name -> kratos.api.gateway.conf.Auth
	4,  // 6: kratos.api.gateway.conf.Bootstrap.rate_limit:type_name -> kratos.api.gateway.conf.RateLimit
	5,  // 7: kratos.api.gateway.conf.Server.http:type_name -> kratos.api.gateway.conf.Server.HTTP
	6,  // 8: kratos.api.gateway.conf.Client.auth:type_name -> kratos.api.gateway.conf.Client.Endpoint
	6,  // 9: kratos.api.gateway.conf.Client.user:type_name -> kratos.api.gateway.conf.Client.Endpoint
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_app_gateway_internal_conf_conf_proto_init() }
func file_app_gateway_internal_conf_conf_proto_init() {
	if File_app_gateway_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_gateway_internal_conf_conf_proto_rawDesc), len(file_app_gateway_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_gateway_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_app_gateway_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_app_gateway_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_app_gateway_internal_conf_conf_proto = out.File
	file_app_gateway_internal_conf_conf_proto_goTypes = nil
	file_app_gateway_internal_conf_conf_proto_depIdxs = nil
}
