// Code generated by hz. DO NOT EDIT.

package auth

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	"kratos-template/app/gateway/biz/handler"
)

func Register(r *server.Hertz, h *handler.AuthHandler) {
	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_v1 := _api.Group("/v1", _v1Mw()...)
			{
				_auth := _v1.Group("/auth", _authMw()...)
				_auth.POST("/login", append(_loginMw(), h.Login)...)
				_auth.POST("/logout", append(_logoutMw(), h.Logout)...)
				_auth.POST("/refresh", append(_refreshMw(), h.Refresh)...)
			}
		}
	}
}
