// Code generated by hz. DO NOT EDIT.

package asset

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	"kratos-template/app/gateway/biz/handler"
)

func Register(r *server.Hertz, h *handler.AssetHandler) {
	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_v1 := _api.Group("/v1", _v1Mw()...)
			_v1.GET("/assets", append(_listassetsMw(), h.ListAssets)...)
			_assets := _v1.Group("/assets", _assetsMw()...)
			_assets.DELETE("/:id", append(_deleteassetMw(), h.DeleteAsset)...)
			_assets.GET("/:id", append(_getassetMw(), h.GetAsset)...)
			_assets.PUT("/:id", append(_updateassetMw(), h.UpdateAsset)...)
			_v1.POST("/assets", append(_createassetMw(), h.CreateAsset)...)
		}
	}
}
