// Code generated by hertz generator.

package asset

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		func(ctx context.Context, c *app.RequestContext) {
			fmt.Println("a ...any")
			c.Next(ctx)
		},
	}
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _assetsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listassetsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteassetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getassetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateassetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createassetMw() []app.HandlerFunc {
	// your code...
	return nil
}
